describe ('Evermos Login', () => {
    it ('Input Username dan password', () => {
        cy.visit('https://evermos.com/home')
        cy.url().should('include','evermos.com/home')
        cy.get('.loggg').should('be.visible')
        cy.get('.loggg').click()
        cy.get('[name="telephone"]').type('6281223334444')
        cy.get('[placeholder="Nama Kamu"]').type('ojan')
        cy.get('[type="password"]').type('12345678')
        cy.get('[class="registration__block"]').click()
        cy.get('.searchBox__input').type('Bukit Kecil')
        cy.get('.list').click()
        cy.get('[type="checkbox"]').should('be.visible')
        cy.get('.btn').should('be.disabled')
        cy.get('.tnc__checkbox > .checkbox > input').click()
        cy.get('.btn').should('be.enabled')
        cy.screenshot()
    })
})